name: Kuaiche Checkin

on:
  schedule:
    - cron: '5 18 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动运行

jobs:
  auto_checkin_kuaiche:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      
    steps:
      - name: 📥 拉取私库代码
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/dailycheckin-kuaiche
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright and browser
        run: npx playwright install --with-deps chromium

      - name: Run checkin script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
        run: npm start

      - name: 🧹 清理旧的工作流运行记录
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 3600
